// components/code-tabs.tsx
"use client";

import * as React from "react";
import { Check, Copy } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";

interface CodeTab {
  label: string;
  value: string;
  code: string;
}

interface CodeTabsProps {
  tabs: CodeTab[];
  defaultValue?: string;
  className?: string;
}

export function CodeTabs({ tabs, defaultValue, className }: CodeTabsProps) {
  const [copied, setCopied] = React.useState(false);
  const [activeTab, setActiveTab] = React.useState(
    defaultValue || tabs[0]?.value || "",
  );

  const activeCode = tabs.find((tab) => tab.value === activeTab)?.code || "";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = activeCode;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <Tabs
      value={activeTab}
      onValueChange={setActiveTab}
      className={cn("w-full", className)}
    >
      <div className="flex items-center justify-between rounded-t-lg border border-b-0 border-border bg-muted/50 px-1">
        <TabsList className="h-auto bg-transparent p-0">
          {tabs.map((tab) => (
            <TabsTrigger
              key={tab.value}
              value={tab.value}
              className="relative rounded-none border-b-2 border-transparent bg-transparent px-4 py-2.5 text-xs font-medium text-muted-foreground shadow-none transition-none data-[state=active]:border-foreground data-[state=active]:bg-transparent data-[state=active]:text-foreground data-[state=active]:shadow-none"
            >
              {tab.label}
            </TabsTrigger>
          ))}
        </TabsList>
        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
          aria-label={copied ? "Copied" : "Copy code to clipboard"}
        >
          {copied ? (
            <>
              <Check className="size-3.5" />
              <span>Copied</span>
            </>
          ) : (
            <>
              <Copy className="size-3.5" />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>
      {tabs.map((tab) => (
        <TabsContent
          key={tab.value}
          value={tab.value}
          className="mt-0 rounded-b-lg border border-border bg-[hsl(var(--foreground)/0.03)] p-4"
        >
          <pre className="overflow-x-auto">
            <code className="font-mono text-sm text-foreground">
              {tab.code.trim()}
            </code>
          </pre>
        </TabsContent>
      ))}
    </Tabs>
  );
}

// src/lib/components/code-tabs.svelte
<script lang="ts">
	import { Check, Copy } from '@lucide/svelte';
	import { cn } from '$lib/utils';

	interface Tab {
		label: string;
		value: string;
		code: string;
	}

	let { tabs, defaultValue, class: className }: { tabs: Tab[]; defaultValue?: string; class?: string } = $props();

	let copied = $state(false);
	let activeTab = $state(defaultValue || tabs[0]?.value || '');

	let activeCode = $derived(tabs.find((tab) => tab.value === activeTab)?.code || '');

	async function handleCopy() {
		try {
			await navigator.clipboard.writeText(activeCode);
			copied = true;
			setTimeout(() => (copied = false), 2000);
		} catch {
			const textarea = document.createElement('textarea');
			textarea.value = activeCode;
			document.body.appendChild(textarea);
			textarea.select();
			document.execCommand('copy');
			document.body.removeChild(textarea);
			copied = true;
			setTimeout(() => (copied = false), 2000);
		}
	}
</script>

<div class={cn('w-full', className)}>
	<div class="flex items-center justify-between rounded-t-lg border border-b-0 border-border bg-muted/50 px-1">
		<div class="flex">
			{#each tabs as tab (tab.value)}
				<button
					class="relative border-b-2 px-4 py-2.5 text-xs font-medium transition-none {activeTab === tab.value
						? 'border-foreground text-foreground'
						: 'border-transparent text-muted-foreground'}"
					onclick={() => (activeTab = tab.value)}
				>
					{tab.label}
				</button>
			{/each}
		</div>
		<button
			onclick={handleCopy}
			class="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
			aria-label={copied ? 'Copied' : 'Copy code to clipboard'}
		>
			{#if copied}
				<Check class="size-3.5" />
				<span>Copied</span>
			{:else}
				<Copy class="size-3.5" />
				<span>Copy</span>
			{/if}
		</button>
	</div>
	{#each tabs as tab (tab.value)}
		{#if activeTab === tab.value}
			<div class="mt-0 rounded-b-lg border border-border bg-[hsl(var(--foreground)/0.03)] p-4">
				<pre class="overflow-x-auto"><code class="font-mono text-sm text-foreground">{tab.code.trim()}</code></pre>
			</div>
		{/if}
	{/each}
</div>
